POST http://localhost:3001/api/tires
Content-Type: application/json
  
    
       
     
        {
        "slika":"https://rabljenegume.com.hr/common/core/images/hgumi/2080/hasznalt_bridgestone_blizzak_lm_30_teli.jpg",
        "tip":"Zimske",
        "marka":"Bridgestone",
        "cijena":0,
        "original":true
    
        }
    