POST http://localhost:3001/api/cars
Content-Type: application/json

{ 
         "slika":"https://www.njuskalo.hr/image-w920x690/auti/mercedes-benz-a-klasa-170-cdi-classic-slika-193411582.jpg",
        "marka":"Mercedes Benz",
        "model":"A 170",
        "godiste":2004,
        "kilometri":205000,
        "vrstaMotora":"Dizel",
        "snagaMotora":70,
        "mjenjac":"Mehanički",
        "boja":"#000000",
        "cijena":3900,
      "gume":"644ed6d3959dd93a15606f89",
      "naplatci":"644ed787d101e3cd74e927cc"
    }